---
title: "Reproducible Research: Peer Assessment 1"
author: "Enzo Alda"
date: "Sunday, December 14, 2014"
output: 
  html_document:
    keep_md: true
---

### Load libraries

```{r}
library(ggplot2);
library(psych);
```

### Load and preprocess data

```{r}
data <- read.csv("activity.csv");
times <- paste(as.character(as.integer(data$interval / 100)), as.character(data$interval %% 100), sep=":");
# Add proper timestamp column
data$time <- strptime(paste(data$date, times), format = "%Y-%m-%d %H:%M");
# Convert *date* field to proper Date
data$date <- as.Date(data$date);
# Add weekday column
data$weekday <- weekdays(data$date);
# Remove useless interval column
data$interval <- NULL;
```

```{r}
# Check data types
str(data);
# show summary
summary(data);
```

### Check mean and median for the total number of steps taken per day

```{r}
# What is mean total number of steps taken per day?
# For this part of the assignment, you can ignore the missing values in the dataset.
# Make a histogram of the total number of steps taken each day
# Calculate and report the mean and median total number of steps taken per day

tapply(data$steps, data$weekday, mean, na.rm = T)
tapply(data$steps, data$weekday, median, na.rm = T)
describeBy(data$steps, data$weekday, na.rm = T)
```

### What is the average daily activity pattern?
```{r}
# Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
# Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
```


### Imputing missing values
```{r}
# Note that there are a number of days/intervals where there are missing values (coded as NA). The presence of missing days may introduce bias into some calculations or summaries of the data.

# Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

# Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.

# Create a new dataset that is equal to the original dataset but with the missing data filled in.

# Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?
```


### Are there differences in activity patterns between weekdays and weekends?
```{r}
# For this part the weekdays() function may be of some help here. Use the dataset with the filled-in missing values for this part.

# Create a new factor variable in the dataset with two levels - "weekday" and "weekend" indicating whether a given date is a weekday or weekend day.

# Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.
```

